### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by zamaudio** [steinbergmedia/vst3sdk#30]
According to the VST3 SDK License page:  https://sdk.steinberg.net/viewtopic.php?f=4&t=282 , there is a:

> Steinberg VST 3 Plug-In SDK Licensing Agreement that you have to sign if you want to develop or host VST 3 Plug-Ins.

However, the same page also explains that the SDK is dual licensed under either Steinberg's License or the GPLv3.

One of the features of the General Public License is that the user does not need to seek permission from anyone to have the four freedoms to run, copy, share and redistribute modified versions of the software in source code form.  Thus requiring the user to sign an agreement with Steinberg before being allowed to have the freedom to make plugins/hosts using the SDK is certainly not in the spirit of the GPLv3.

Can you please clarify if Steinberg waives the requirement for any user to sign the agreement if they want to create plugins or hosts using the SDK - if the user chooses GPLv3 as the license?

**Comment by scheffle** [comment]
You either choose the Steinberg or GPLv3 license. If you choose the Steinberg license, then you need to sign the agreement and can distribute closed source plugins/hosts. If you choose the GPLv3 license then you don't need to sign the agreement, but you have to open source your plugin/host so that it anyone can build it from source.
I hope this makes it clear. Other popular libraries like QT or Juce also provides dual licenses like the one in the VST3 SDK.

**Comment by zamaudio** [comment]
Thanks!
